import fs from "fs-extra";
import path from "path";
import { optimize } from "svgo";
import { parse, HTMLElement } from "node-html-parser";

const cwd = process.cwd();
const inputPath = path.join(cwd, "other", "svg");
const outputPath = path.join(cwd, "public", "icons");
const typeDir = path.join(cwd, "src/types");
const shouldVerboseLog = process.argv.includes("--log=verbose");
const logVerbose = shouldVerboseLog ? console.log : () => {};
let filesCount = 0;

async function getAllSvgFiles(dir: string): Promise<string[]> {
  const dirents = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    dirents.map((dirent) => {
      const res = path.resolve(dir, dirent.name);
      if (dirent.isDirectory()) {
        return getAllSvgFiles(res);
      }
      return dirent.name.endsWith(".svg") ? res : null;
    })
  );
  return files.flat().filter(Boolean) as string[];
}

function iconName(filePath: string): string {
  return path.basename(filePath, ".svg");
}

function setAttributesToCurrentColor(svg: HTMLElement): void {
  svg.querySelectorAll("[fill],[stroke]").forEach((el) => {
    ["fill", "stroke"].forEach((attr) => {
      const value = el.getAttribute(attr);
      if (value && value !== "none" && value !== "currentColor") {
        el.setAttribute(attr, "currentColor");
      }
    });
  });
}

async function processSvgFile(
  filePath: string,
  isCustomize: boolean
): Promise<string> {
  const svgContent = await fs.readFile(filePath, "utf-8");
  const isDoNotOptimize = filePath.includes("do-not-optimize");
  let optimized = svgContent;
  if (!isDoNotOptimize) {
    optimized = optimize(svgContent, { multipass: true }).data;
  }
  const root = parse(optimized);
  const svg = root.querySelector("svg");
  if (!svg) throw new Error(`No SVG element found in ${filePath}`);
  svg.tagName = "symbol";
  svg.setAttribute("id", iconName(filePath));
  svg.removeAttribute("xmlns");
  svg.removeAttribute("xmlns:xlink");
  svg.removeAttribute("version");
  svg.removeAttribute("width");
  svg.removeAttribute("height");
  if (isCustomize) {
    setAttributesToCurrentColor(svg);
  }
  return svg.toString();
}

async function getFileSize(filePath: string): Promise<number> {
  try {
    const stats = await fs.stat(filePath);
    return stats.size;
  } catch {
    return 0;
  }
}

async function buildAllSprites() {
  await fs.ensureDir(outputPath);
  await fs.ensureDir(typeDir);
  const allDirents = await fs.readdir(inputPath, { withFileTypes: true });
  const folders = allDirents
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name);
  let allIconNames: string[] = [];
  let originalTotalSize = 0;
  let optimizedTotalSize = 0;

  await Promise.all(
    folders.map(async (folder) => {
      const folderPath = path.join(inputPath, folder);
      const isCustomize = folder === "customize";
      const files = await getAllSvgFiles(folderPath);

      // Calculate original size
      const originalSizes = await Promise.all(files.map(getFileSize));
      originalTotalSize += originalSizes.reduce((a, b) => a + b, 0);

      const symbols = await Promise.all(
        files.map((file) => processSvgFile(file, isCustomize))
      );
      filesCount += symbols.length;
      const sprite = [
        `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: none;">`,
        ...symbols,
        `</svg>`,
      ].join("\n");
      const spritePath = path.join(outputPath, `${folder}-sprite.svg`);
      await fs.writeFile(spritePath, sprite, "utf8");

      // Calculate optimized size
      const optimizedSize = await getFileSize(spritePath);
      optimizedTotalSize += optimizedSize;

      logVerbose(`✅ Generated sprite for '${folder}'`);
      allIconNames.push(...files.map(iconName));
    })
  );
  const typeOutputFilepath = path.join(typeDir, "name.d.ts");
  const stringifiedIconNames = Array.from(new Set(allIconNames)).map((name) =>
    JSON.stringify(name)
  );
  const typeOutputContent = `// This file is generated by npm run build:icons
export type IconName =
\t| ${stringifiedIconNames.join("\n\t| ")};
`;
  await writeIfChanged(typeOutputFilepath, typeOutputContent);
  logVerbose(
    `Manifest saved to ${path.relative(process.cwd(), typeOutputFilepath)}`
  );
  const iconManifest: Record<string, string> = {};
  for (const folder of folders) {
    const files = await getAllSvgFiles(path.join(inputPath, folder));
    files.forEach((file) => {
      const name = iconName(file);
      iconManifest[name] = `${folder}-sprite.svg`;
    });
  }
  await fs.writeFile(
    path.join(process.cwd(), "src", "types", "icon-manifest.ts"),
    `const iconManifestData = ${JSON.stringify(
      iconManifest,
      null,
      2
    )};\nexport default iconManifestData;\n`
  );
  console.log(`✅ Generated ${filesCount} icons`);

  // Show % size saved
  if (originalTotalSize > 0) {
    const percentSaved =
      ((originalTotalSize - optimizedTotalSize) / originalTotalSize) * 100;
    console.log(
      `💾 Size saved: ${percentSaved.toFixed(2)}% (${(
        originalTotalSize / 1024
      ).toFixed(2)} KB → ${(optimizedTotalSize / 1024).toFixed(2)} KB)`
    );
  }
}

async function writeIfChanged(filepath: string, newContent: string) {
  const currentContent = await fs.readFile(filepath, "utf8").catch(() => "");
  if (currentContent === newContent) return false;
  await fs.writeFile(filepath, newContent, "utf8");
  return true;
}

buildAllSprites().catch((err) => {
  console.error("❌ Error building sprites:", err);
});
